#!/bin/sh
./compile-app &&
ghc -isrc:tests --make -fwarn-unused-imports -Werror tests/QCTests.hs &&
ghc -isrc:tests --make -fwarn-unused-imports -Werror tests/UnitTests.hs &&
./tests/QCTests &&
./tests/UnitTests
